global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: laravel_metrics
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
      - targets:
          - laravel-web:80
